# Setup
title: Saeed Mosavyzadeh
tagline: "Exploring the World"
description: 'main as <a href="https://saeedmosavyzadeh.ir" target="_blank">saeedmosavyzadeh.ir</a>.'
url: "https://github.saeedmosavyzadeh.ir"
baseurl: ""
paginate: 5
permalink: pretty

# About/contact
author:
  name: Saeed Mosavyzadeh
  url:
  email: contact@saeedmosavyzadeh.ir

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version: 1.1.0
google_analytics_id: #UA-XXXX-Y

# for posting new
future: true
